# Generated by Django 4.0.2 on 2022-02-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_bookmark_like_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='reply',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='feed_id',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['feed_id'], name='content_rep_feed_id_49ae3d_idx'),
        ),
    ]
