# Generated by Django 4.0.2 on 2022-02-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_reply_content_reply_content_reply_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='content',
            new_name='reply_content',
        ),
    ]
