# Generated by Django 4.0.2 on 2022-02-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_content_reply_reply_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('is_like', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddIndex(
            model_name='feedlike',
            index=models.Index(fields=['feed_id'], name='content_fee_feed_id_1c82cf_idx'),
        ),
        migrations.AddIndex(
            model_name='feedlike',
            index=models.Index(fields=['email'], name='content_fee_email_3901d6_idx'),
        ),
    ]
