# Generated by Django 4.0.2 on 2022-02-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_feedlike_delete_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
