# Generated by Django 4.0.2 on 2022-02-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_feed_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='nickname',
        ),
    ]
