# Generated by Django 4.0.2 on 2022-02-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_user_id_reply_nickname'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reply',
            name='content_rep_feed_id_49ae3d_idx',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='feed_id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='nickname',
        ),
        migrations.AddField(
            model_name='reply',
            name='content_id',
            field=models.IntegerField(default=0),
        ),
    ]
