# Generated by Django 4.0.2 on 2022-02-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_reply_content_rep_feed_id_49ae3d_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='content_id',
            new_name='feed_id',
        ),
    ]
